version: "3.9"

services:
  postgres:
    container_name: booking-service-database
    image: postgres:13.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    container_name: booking-service-backend
    depends_on:
      - postgres
    build:
      context: ./backend
    volumes:
      - .:/code
    ports:
      - "80:80"
    restart: always
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  app:
    container_name: booking-service-app
    depends_on:
      - backend
    build:
      context: ./app
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    restart: always
    environment:
      BACKEND_URL: ${BACKEND_URL}


volumes:
  postgres_data: